shape: sequence_diagram

ChatBar -> Chat: submitQuestion()

ChatBar -> ChatBar: cleanBar()

Chat -> Chat: createUserMessage()

Chat -> Chat: setSkeletonMessage()

Chat -> Page: submitQuestion()

Page -> Backend.ack: submitQuestion()
Backend.ack -> Page

Page -> Code: setCode()
Code -> CodeEditor: setCode()

Page -> Chat: setAiMessage()
Chat -> Chat: deleteSkeletonMessage()
Chat -> Chat: createAiExplanation()
